def run():
    words = [
        "False",
        "class",
        "finally",
        "is",
        "return",
        "None",
        "continue",
        "for",
        "lambda",
        "try",
        "True",
        "def",
        "from",
        "nonlocal",
        "while",
        "and",
        "del",
        "global",
        "not",
        "with",
        "as",
        "elif",
        "or",
        "yield",
        "assert",
        "else",
        "import",
        "pass",
        "break",
        "except",
        "if",
        "raise",
        "await",
        "async",
        "in",
        "abs",
        "delattr",
        "hash",
        "memoryview",
        "set",
        "all",
        "dict",
        "help",
        "min",
        "setattr",
        "any",
        "dir",
        "hex",
        "next",
        "slice",
        "ascii",
        "divmod",
        "id",
        "object",
        "sorted",
        "bin",
        "enumerate",
        "input",
        "oct",
        "staticmethod",
        "bool",
        "eval",
        "int",
        "open",
        "str",
        "breakpoint",
        "exec",
        "isinstance",
        "ord",
        "sum",
        "bytearray",
        "filter",
        "issubclass",
        "pow",
        "super",
        "bytes",
        "float",
        "iter",
        "print",
        "tuple",
        "callable",
        "format",
        "len",
        "property",
        "type",
        "chr",
        "frozenset",
        "list",
        "range",
        "vars",
        "classmethod",
        "getattr",
        "locals",
        "repr",
        "zip",
        "compile",
        "globals",
        "map",
        "reversed",
        "__import__",
        "complex",
        "hasattr",
        "max",
        "round"
    ]

    finaldict = "[\n"

    template="\t{},\n"

    lang = input("Language: ")
    langcode = input("ISO639.2 Language code: ")

    for i in words:
        print("Word to translate: "+i)
        newword=input("Translation: ")
        finaldict+=template.format(newword)

    finaldict+="]"
    print(chr(27) + "[2J")
    print("Language: {} ({})\n\n".format(lang, langcode))
    print(finaldict)
